name: Build Windows Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.x'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Setup LLVM/Clang
        run: choco install llvm -y

      - name: Setup VCPKG
        run: |
          vcpkg install libvpx:x64-windows libyuv:x64-windows opus:x64-windows

      - name: Build Windows
        env:
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
        run: |
          cd flutter
          flutter pub get
          flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Suporte-Remoto-Windows
          path: flutter/build/windows/x64/runner/Release/
