name: Build Windows Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: 1. Baixar Codigo Fonte
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 2. Preparar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.x'

      - name: 3. Preparar Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: 4. Instalar Compilador LLVM
        run: choco install llvm -y

      - name: 5. Compilar Bibliotecas de Video
        run: |
          vcpkg install libvpx libyuv opus --triplet x64-windows-static
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV

      - name: 6. Gerar o .EXE Final
        env:
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
        run: |
          cd flutter
          flutter pub get
          flutter build windows --release

      - name: 7. Salvar o Executavel para Download
        uses: actions/upload-artifact@v4
        with:
          name: Suporte-Remoto-Empresa
          path: flutter/build/windows/x64/runner/Release/
