name: Build Windows Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Setup LLVM & InnoSetup
        run: |
          choco install llvm innosetup -y

      - name: Setup VCPKG (Official Action)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'a42af01b72c28c8e1d7b48104b33e4f286a558d7'
          packages: 'libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.x'

      - name: Build Windows Executable
        env:
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
        run: |
          cd flutter
          flutter pub get
          flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Suporte-Remoto-Windows
          path: flutter/build/windows/x64/runner/Release/
